account_id                               = "{{.awsID}}"
enable_keypair_output                    = "false"
hosted_zone                              = "{{.hostedZone}}"
project_fqdn                             = "{{.projectName}}.{{.hostedZone}}"
project_name                             = "{{.projectName}}"
enable_elasticsearch                     = "true"
create_elasticsearch_linked_service_role = "false"
region                                   = "{{.region}}"