variable "enable_cloudwatch_metrics" {}
variable "environment_abbr" {}
variable "image" {}
variable "image_repo" {}
variable "log_level" {}
variable "model_data_url" {}
variable "model_name" {}
variable "project_name" {}
variable "region" {}
variable "sagemaker_image_name" {}
variable "sagemaker_role" {}
variable source_directory {}
variable "stack_name" {}