properties([
  parameters([
    booleanParam(name: 'EXEC_BUILD', defaultValue: true, description: 'Should execute build'),
    booleanParam(name: 'EXEC_DEPLOY', defaultValue: true, description: 'Should execute deploy'),
    booleanParam(name: 'EXEC_INTEGRATIONTEST', defaultValue: true, description: 'Should execute integration tests'),
    booleanParam(name: 'EXEC_UNITTEST', defaultValue: true, description: 'Should execute unit tests'),
    stringParam(name: 'BUILD_DIRECTORY', defaultValue: 'none', description: 'Unique directory for this Jenkins build'),
    stringParam(name: 'VPC_NAME', defaultValue: 'none', description: 'Environment/application VPC being deployed to')
  ])
])

node {
  dir(params.BUILD_DIRECTORY + "/app") {
    stage('Build') {
      if (params.EXEC_BUILD) {
        sh 'npm i'
        sh 'NODE_OPTIONS="--max-old-space-size=4096" npm run build'
      }
    }
    stage('Unit Tests') {
      if (params.EXEC_UNITTEST) {
        try {
          withEnv(["JEST_JUNIT_OUTPUT=./jest-test-results.xml"]) {
            sh 'npm run test-ci'
          }
        }
        finally {
          junit 'jest-test-results.xml'
        }
      }
    }
    stage('Deploy To Integration') {
      if (params.EXEC_DEPLOY) {
        env.VPC_NAME = params.VPC_NAME
        sh 'sh .deploy.sh ${VPC_NAME}'
      }
    }
    stage('Integration Tests') {
      if (params.EXEC_INTEGRATIONTEST) {
        echo "Integration Tests here"
      }
    }
  }
}
