import {
    autoGeneratedHashKey,
    hashKey,
    rangeKey,
    table,
    attribute
} from '@aws/dynamodb-data-mapper-annotations';

const environmentAbbreviation = process.env.ENV_ABBR || 'int';
const tableName = 'pac-{{.projectName}}-' + environmentAbbreviation + '-{{.serviceName}}';

/**
 * A {{.serviceNamePascal}} object - but what exactly is a {{.serviceNamePascal}}?
 */
@table(tableName)
export class {{.serviceNamePascal}} {

    /**
     * Auto generated hash key of {{.serviceName}}
     */
    @autoGeneratedHashKey()
    id: string;

     /**
     * How many buttons does this {{.serviceNamePascal}} have?
     */
    @attribute()
    buttons: number;

    /**
     * How many axles does this {{.serviceNamePascal}} have?
     */
    @attribute()
    axles: number;
}
