properties([
  parameters([
    booleanParam(name: 'EXEC_BUILD', defaultValue: true, description: 'Should execute build'),
    booleanParam(name: 'EXEC_DEPLOY', defaultValue: true, description: 'Should execute deploy'),
    booleanParam(name: 'EXEC_INTEGRATIONTEST', defaultValue: true, description: 'Should execute integration tests'),
    booleanParam(name: 'EXEC_UNITTEST', defaultValue: true, description: 'Should execute unit tests'),
    stringParam(name: 'BUILD_DIRECTORY', defaultValue: 'none', description: 'Unique directory for this Jenkins build'),
    stringParam(name: 'VPC_NAME', defaultValue: 'none', description: 'Environment/application VPC being deployed to')
  ])
])

node {
  dir(params.BUILD_DIRECTORY + "/services") {
    stage('Build') {
      if (params.EXEC_BUILD) {
        sh 'sh .build.sh'
      }
    }
    stage('Unit Test') {
      if (params.EXEC_UNITTEST) {
        sh 'sh .test.sh'
      }
    }
    stage('Deploy To Integration') {
      if (params.EXEC_DEPLOY) {
        env.VPC_NAME = params.VPC_NAME
        sh 'sh .deploy.sh ${VPC_NAME}'
      }
    }
  }
}
