pipeline {
  parameters {
    booleanParam(name: 'EXEC_BUILD', defaultValue: true, description: 'Should execute build')
    booleanParam(name: 'EXEC_DEPLOY', defaultValue: true, description: 'Should execute deploy')
    booleanParam(name: 'EXEC_INTEGRATIONTEST', defaultValue: true, description: 'Should execute integration tests')
    booleanParam(name: 'EXEC_UNITTEST', defaultValue: true, description: 'Should execute unit tests')
  }
  agent any
  stages {
    stage('Build') {
      steps {
        script {
          if (params.EXEC_BUILD){
            sh 'cd svc/$JOB_NAME && sh .build.sh'
          }
        }
      }
    }
    stage('Unit Tests') {
      steps {
        script {
          if (params.EXEC_UNITTEST){
            sh 'cd svc/$JOB_NAME && sh .test.sh'
          }
        }
      }
    }
    stage('Deploy To Integration') {
      steps {
        script {
          if (params.EXEC_DEPLOY){
            sh 'cd svc/$JOB_NAME && sh .deploy.sh'
          }
        }
      }
    }

    stage('Integration Tests') {
      steps {
        script {
          if (params.EXEC_INTEGRATIONTEST){
            echo "Integrate"
          }
        }
      }
    }
  }
}
