application_cidr_block = "{{ .vpcCidrBlock }}"
environment_abbr       = "{{ .environmentAbbr }}"
environment_name       = "{{ .environmentName }}"
es_instance_type       = "t2.medium.elasticsearch"
project_fqdn           = "{{ .projectFqdn }}"
project_name           = "{{ .projectName }}"
