import {
    autoGeneratedHashKey,
    hashKey,
    rangeKey,
    table,
    attribute
} from '@aws/dynamodb-data-mapper-annotations';

/**
 * A {{.serviceNamePascal}} object - but what exactly is a {{.serviceNamePascal}}?
 */
@table('pac-{{.projectName}}-i-{{.serviceName}}')
export class {{.serviceNamePascal}} {

    /**
     * Auto generated hash key of {{.serviceName}}
     */
    @autoGeneratedHashKey()
    id: string;

     /**
     * How many buttons does this {{.serviceNamePascal}} have?
     */
    @attribute()
    buttons: number;

    /**
     * How many axles does this {{.serviceNamePascal}} have?
     */
    @attribute()
    axles: number;
}